all:	BubbleSort IteratorDemo

BubbleSort:	BubbleSort.cpp
	g++ -std=c++11 -Wall -O3 -I ../../doctest -DDOCTEST_CONFIG_DISABLE BubbleSort.cpp -o BubbleSort

IteratorDemo:	IteratorDemo.cpp
	g++ -std=c++11 -Wall -O3 -I ../../doctest -DDOCTEST_CONFIG_DISABLE IteratorDemo.cpp -o IteratorDemo

clean:
	rm BubbleSort IteratorDemo